### PR TITLE
Fix #139

### LINKED ISSUE #139: Method call in a class initializer is not implemented
# Tell me your versions
- **PHP**
```
PHP 7.3.5 (cli) (built: May  2 2019 12:40:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies
```

- **JDK**
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
```

- **PHPJava**
77668dbc81dc27dd8c195a62c215add82311d60e

# Summary
A method call in a class initializer throws an exception.

# Code
```java
class Cat
{
    protected String comment;
 
    public void meow()
    {
        System.out.println(this.comment);
    }
}

class HelloCat
{
    public static void main(String[] args)
    {
        new Cat() {{
            this.comment = "Hello, I am a cat.";
            meow();
        }};
    }
}
```

Find a reproducible sample here: https://github.com/chitoku-k/php-java-test/commit/8462d5b93f630e991fa673adb452a7698f2875bf

# Expected
```
Hello, I am a cat.
```

# Actual
```
PHP Fatal error:  Uncaught PHPJava\Packages\java\lang\NoSuchMethodException: Call to undefined method meow. in /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php:369
Stack trace:
#0 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php(89): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->findMethod('meow')
#1 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Cache/Cache.php(13): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->PHPJava\Core\JVM\Invoker\{closure}()
#2 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable.php(91): PHPJava\Core\JVM\Cache\Cache->fetchOrPush('meow.', Object(Closure))
#3 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Kernel/Mnemonics/_invokevirtual.php(59): PHPJava\Core\JVM\Invoker\DynamicMethodInvoker->call('meow')
#4 /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Core/JVM/Invoker/Invokable. in /Users/chitoku/Test/php-java-playground/vendor/php-java/php-java/src/Kernel/Mnemonics/_invokespecial.php on line 96
```

### PR DESCRIPTION
**Pull request by m3m0r7**

### CODE REVIEW

File: src/Core/JVM/Invoker/Invokable.php [hunk 1]
```diff
@@ -82,6 +85,8 @@ function () use ($name, $arguments) {
             }
         );
 
+        $currentConstantPool = $method->getConstantPool() ?? $currentConstantPool;
```
Comment (m3m0r7) [inline src/Core/JVM/Invoker/Invokable.php:88]: A method has a unique Constant Pool reference.
Therefore, by adding this code, the method can be refering the Constant Pool in targeted class.
